## cartridge.properties for cartridge plugin_custom_AIstyleguide
    demandware.cartridges.plugin_custom_AIstyleguide.multipleLanguageStorefront=true
    demandware.cartridges.plugin_custom_AIstyleguide.id=plugin_custom_AIstyleguide
    