# cartridge.properties for cartridge plugin_shopper_agent
# Fri Mar 01 16:11:58 PST 2024
demandware.cartridges.plugin_shopper_agent.multipleLanguageStorefront=true
demandware.cartridges.plugin_shopper_agent.id=plugin_shopper_agent
demandware.cartridges.plugin_shopper_agent.version=1.0.0
